### ISSUE TITLE
CSV mimetypes are not just "text/csv"

### ISSUE THREAD

**Issue by bondt** [leo-holanda/logcharts.io#1]
My browser reports CSV files as mimetype `application/vnd.ms-excel`. This fails in the `isCSV` function. Would you mind adding that?

https://github.com/leo-holanda/logcharts.io/blob/635159e9fecd381e1308cd2f365d77a8b0f57dac/public/javascripts/helper.js#L41

So replace that function with the following:
```
export function isCSV(file){
  if (file.type == "text/csv" || file.type == "application/vnd.ms-excel" || !file.type) return true;
}
```

Thanks!

**Comment by leo-holanda** [comment]
Hey! Thanks for the issue! I changed the code, if some bug appears again please let me know!

**Comment by bondt** [comment]
You're welcome! Haven't had a lot of time to check it out further, but it works now.
