### ISSUE TITLE
v7 not supported?

### ISSUE THREAD

**Issue by 1oh1** [leo-holanda/logcharts.io#2]
Could you mention which version of HWiNFO is supported? The logs that I got from HWiNFO v7.07 wasn't able to load and I see the "Please send only logs from HWInfo!" message

**Comment by leo-holanda** [comment]
Hey, thanks for letting me know! I downloaded the 7.07-4510 version and it seems to work fine. I have checked the CSV file and didn't found anything that has changed significantly that would break the code. 

The first thing that comes to mind is an encoding problem. I am already thinking of a solution for this and will try to implement it today. If you want, you could try sending me your CSV file and I would take a look!

**Comment by 1oh1** [comment]
Sure thing. Thanks for the speedy response and for looking into this. I've attached a short sensor log from HWiNFO v7.07-4505.

I was not able to load this log file: [test-log-hwinfo-v707.CSV](https://github.com/leo-holanda/logcharts.io/files/6909638/test-log-hwinfo-v707.CSV)

**Comment by leo-holanda** [comment]
I was able to create a chart with your log and the website should be updated already. If some bug appears or if there's anything more I can help with, just leave a message!

**Comment by 1oh1** [comment]
I can confirm that I'm able to load my log files. Thank you for the fix! However I noticed that the example is now broken. If I click on 
"See an example" I just see a loading bar and the "Please, select the default field" message pop up in the back, all blurred out.

**Comment by leo-holanda** [comment]
Yes, I should have removed the loading overlay, now it should work fine. Thanks for letting me know!

**Comment by 1oh1** [comment]
You're welcome. I'll close the issue now since it's fixed.
