### ISSUE TITLE
Running inside container

### ISSUE THREAD

**Issue by Baryczka** [leo-holanda/logcharts.io#3]
Would be possible to add docker-compose.yml file or Dockerfile that would allow to run it inside container?
I would like to avoid installing `npm` and all its dependencies

**Comment by leo-holanda** [comment]
Sorry for answering after some time, I didn't receive a notification for this issue! :sweat: Yes, absolutely! I did some changes with the build and didn't update the current Dockerfile. I'm gonna push some commits to fix that!

**Comment by leo-holanda** [comment]
@Baryczka the master branch now has a docker-compose file. I made some testing and everything seems to work fine but please let me know If you have some problem. The container port is mapped to 8080 so it's visible at http://localhost:8080/

**Comment by Baryczka** [comment]
No worries at all it was not late reply ;) It works perfectly so far! I believe ticket can be closed as done. 🥳 

But I will take an opportunity and ask something regarding UI.
There is option to add metric to the stack but I don't know how to remove it? There are radio buttons, what is the usage of them?

**Comment by leo-holanda** [comment]
That's great! Thanks for creating it!

Yes, there's no option to remove unfortunately. But it's easy to do and I don't know why I haven't added it already 🤔 I'm gonna push some commits to add this functionality!

The radio buttons means that you can only change one line at a time. So if you want to change the data that a line is showing, first you need to select the radio button corresponding to the line you want to change and then click the button corresponding to the data you want to see

**Comment by leo-holanda** [comment]
@Baryczka You know what's funny? The remove line feature was there all time lol I changed the icons provider and forgot to change the trash can icon identifier to the new provider. Because of this, the icon was not appearing 🫠

I have tested and it should be working now but please let me know if you find any issues!
